# Задание 4.5.1

In [1]:
from scipy.optimize import linprog
import numpy as np

In [2]:
cost = np.array([
    [3, 12, 9,1,7],
    [2, 4, 11,2,10],
    [7,14,12,5,8]
])
stock = np.array([350, 330,270])
demand = np.array([210,170,220,150,200])
num_warehouse = 3
num_clients = 5

$x_{ij}$ - сколько забирается со i склада клиенту j  
$$f = \sum_{i,j} cost_{ij} * x_{ij}$$

In [3]:
c = cost.flatten()
print(c) 

[ 3 12  9  1  7  2  4 11  2 10  7 14 12  5  8]


Для каждого склада количество взятых предметов должно быть меньше, чем на складе:

$$\forall i: \sum_j x_{ij} \leq stock_i$$

In [4]:
A = []
b = []
for i in range(0, num_warehouse):
    A.append([0] * (num_clients * i) + [1] * num_clients + [0] * (num_clients * (num_warehouse - i - 1)))
    b.append(stock[i])
A = np.asarray(A)
b = np.asarray(b)
print(A)
print(b)

[[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]]
[350 330 270]


Для каждого клиента количество приобретаемых товаров должно быть больше на единицу, чем спрос:

$$\forall j: \sum_i x_{ij} \geq demand_j$$

Который также:

$$\forall j: - \sum_i x_{ij} \leq -demand_j$$

In [5]:
A = A.tolist()
b = b.tolist()
for j in range(0, num_clients):
    A.append(([0] * j + [-1] + [0] * (num_clients - j - 1)) * num_warehouse)
    b.append(-demand[j])
A = np.asarray(A)
b = np.asarray(b)
print(A)
print(b)
print(c)

[[ 1  1  1  1  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  1  1  1  1  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  1  1  1  1]
 [-1  0  0  0  0 -1  0  0  0  0 -1  0  0  0  0]
 [ 0 -1  0  0  0  0 -1  0  0  0  0 -1  0  0  0]
 [ 0  0 -1  0  0  0  0 -1  0  0  0  0 -1  0  0]
 [ 0  0  0 -1  0  0  0  0 -1  0  0  0  0 -1  0]
 [ 0  0  0  0 -1  0  0  0  0 -1  0  0  0  0 -1]]
[ 350  330  270 -210 -170 -220 -150 -200]
[ 3 12  9  1  7  2  4 11  2 10  7 14 12  5  8]


In [6]:
linprog(c=c, A_ub=A, b_ub=b)

     con: array([], dtype=float64)
     fun: 5089.9997160905
 message: 'Optimization terminated successfully.'
     nit: 6
   slack: array([ 2.11893488e-05,  1.99639632e-05,  1.62943373e-05, -1.27103378e-05,
       -1.02694542e-05, -1.33294557e-05, -9.03317411e-06, -1.21052275e-05])
  status: 0
 success: True
       x: array([4.99999997e+01, 4.60514010e-07, 1.49999989e+02, 1.49999989e+02,
       1.42710666e-06, 1.59999987e+02, 1.69999989e+02, 1.25774715e-06,
       2.40453261e-06, 8.73862967e-07, 8.74236877e-07, 5.33615530e-07,
       6.99999967e+01, 3.30200393e-08, 1.99999986e+02])

Минимальные затраты состовляют 5090