In [22]:
import numpy as np
from scipy.optimize import linprog

c = np.array([-300, -250, -560, -480])
print(f'Коэффициенты целевой функции: {c}')
A_ub = np.array([[3, 5, 2, 4], [22, 14, 18,30],[10,14,8,16]])
print(f'Коэффициенты условия ограничений неравенства:\n {A_ub}')
b_ub = np.array([60, 400, 128])
print(f'Коэффициенты свободных членов:\n {b_ub}')
res = linprog(c, A_ub, b_ub)
print(f'Максимальное значение x: {max(res.x)}, оптимальное решение: {-1 * res.fun}')


Коэффициенты целевой функции: [-300 -250 -560 -480]
Коэффициенты условия ограничений неравенства:
 [[ 3  5  2  4]
 [22 14 18 30]
 [10 14  8 16]]
Коэффициенты свободных членов:
 [ 60 400 128]
Максимальное значение x: 15.999999999920004, оптимальное решение: 8959.999999955886
