In [1]:
import numpy as np

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[ 8,  5,  5],
       [ 9,  5, 11],
       [11,  9,  9]])

In [4]:
B

array([[ 1, -1,  3],
       [ 3, -1, -2],
       [ 2,  0,  0]])

In [5]:
# Поэлементное умножение
A*B

array([[  8,  -5,  15],
       [ 27,  -5, -22],
       [ 22,   0,   0]])

In [6]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[ 33 -13  14]
 [ 46 -14  17]
 [ 56 -20  15]]


In [7]:
# Матричное умножение
np.dot(A,B)

array([[ 33, -13,  14],
       [ 46, -14,  17],
       [ 56, -20,  15]])

In [8]:
# Матричное умножение
A@B

array([[ 33, -13,  14],
       [ 46, -14,  17],
       [ 56, -20,  15]])

In [9]:
# Порядок умножения AB != BA
B@A

array([[ 32,  27,  21],
       [ -7,  -8, -14],
       [ 16,  10,  10]])

In [10]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 9  5 10  6  9]
 [ 6 10 11  6  7]
 [ 6 11  6 10  5]]
B:
 [[ 3  3]
 [ 0 -2]
 [ 2  3]
 [ 1 -2]
 [-2  0]]


In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[35, 35],
       [32, 19],
       [30, -6]])

In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [ ]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

In [14]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-3  3  3  0]
 [-3  2  0 -2]
 [ 3  1 -3  3]
 [ 3  0 -3 -1]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-3  6  0  0]
 [-3  4  0  2]
 [ 3  2  0 -3]
 [ 3  0  0  1]]
DA:
 [[-3  3  3  0]
 [-6  4  0 -4]
 [ 0  0  0  0]
 [-3  0  3  1]]


In [13]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [ ]:
b@A

In [16]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [17]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [18]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [19]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])