In [7]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [6]:
С = np.array([[1,0.9922],[0.9922,1]])
np.linalg.eig(С)

(array([1.9922, 0.0078]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [22]:
x1 = np.array([1,2,1,1])
x2 = np.array([70,130,65,60])


In [23]:
x1_c = x1 - np.mean(x1)
x2_c = x2 - np.mean(x2)
print(x1_c, x2_c)

[-0.25  0.75 -0.25 -0.25] [-11.25  48.75 -16.25 -21.25]


In [24]:
x1_n = x1_c / np.linalg.norm(x1_c)
x2_n = x2_c / np.linalg.norm(x2_c)
print(x1_n, x2_n)

[-0.28867513  0.8660254  -0.28867513 -0.28867513] [-0.19829369  0.85927267 -0.28642422 -0.37455475]


In [30]:
F = (x1_n + x2_n) 
F

array([-0.48696883,  1.72529807, -0.57509936, -0.66322989])