Создание массива 

In [4]:
import numpy as np

n1 = np.array([1,4,5,3,2])
print(n1)

[1 4 5 3 2]


Создание массива целых цисел длины 10, заполенный нулями

In [5]:
n2 = np.zeros(10, dtype=int)
print(n2)

[0 0 0 0 0 0 0 0 0 0]


Создание массива размером 3 х 5, заполненный единицами

In [6]:
n3 = np.ones((3,5), dtype=float)
print(n3)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Создание массива целых цисел длины 10, заполенный значением 3.14

In [7]:
n4 = np.full((3,5), 3.14)
print(n4)


[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


Создаем массив, заполенный линейной последовательностью, начинающийся с 0 и заканчивающейся 20, с шагом 2

In [11]:
n5 = np.arange(0,20,2)
print(n5)


[ 0  2  4  6  8 10 12 14 16 18]


Создаем массив (сетку) из пяти значений, равномерно располагающихся между 0 и 1

In [12]:
n6 = np.linspace(0,1,5)
print(n6)

[0.   0.25 0.5  0.75 1.  ]


Создаем массив размером 3 х 3 равномерно распределённых случайных значений от 1 до 1 

In [15]:
n7 = np.random.random((3,3))
print(n7)

[[0.02009178 0.60177296 0.39713881]
 [0.4363787  0.3529965  0.02860591]
 [0.82236863 0.05990986 0.5570449 ]]


Созданием массив размером 3 х 3 нормально распределенных случайных значений с медианой 0 и стандартным отклонением 1

In [18]:
n8 = np.random.normal(0,1,(3,3))
print(n8)

[[ 1.07328855 -0.15331418  1.35509678]
 [ 0.63191944  1.44590009  0.52968564]
 [-0.85764448  0.03561526  0.27873815]]


Созданием массив размером 3 х 3 случайных целых чисел в промежутке [0;10)

In [20]:
n9 = np.random.randint(0,10,(3,3))
print(n9)

[[8 7 0]
 [9 6 9]
 [4 1 4]]


Созаем единичную матрицу размером 3 х 3

In [21]:
n10 = np.eye(3)
print(n10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
