Создание массива 

In [2]:
import numpy as np

n1 = np.array([1,4,5,3,2])
print(n1)

[1 4 5 3 2]


Создание массива целых цисел длины 10, заполенный нулями

In [3]:
n2 = np.zeros(10, dtype=int)
print(n2)

[0 0 0 0 0 0 0 0 0 0]


Создание массива размером 3 х 5, заполненный единицами

In [4]:
n3 = np.ones((3,5), dtype=float)
print(n3)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Создание массива целых цисел длины 10, заполенный значением 3.14

In [5]:
n4 = np.full((3,5), 3.14)
print(n4)


[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


Создаем массив, заполенный линейной последовательностью, начинающийся с 0 и заканчивающейся 20, с шагом 2

In [6]:
n5 = np.arange(0,20,2)
print(n5)


[ 0  2  4  6  8 10 12 14 16 18]


Создаем массив (сетку) из пяти значений, равномерно располагающихся между 0 и 1

In [7]:
n6 = np.linspace(0,1,5)
print(n6)

[0.   0.25 0.5  0.75 1.  ]


Создаем массив размером 3 х 3 равномерно распределённых случайных значений от 1 до 1 

In [8]:
n7 = np.random.random((3,3))
print(n7)

[[0.04543945 0.83378415 0.83655643]
 [0.20488242 0.55331548 0.45249888]
 [0.97512313 0.02223649 0.91403568]]


Созданием массив размером 3 х 3 нормально распределенных случайных значений с медианой 0 и стандартным отклонением 1

In [9]:
n8 = np.random.normal(0,1,(3,3))
print(n8)

[[ 0.91789505  0.29844641 -1.4005406 ]
 [ 0.0213368   0.40400566  0.39158827]
 [-0.31539712  0.55684595 -0.2690796 ]]


Созданием массив размером 3 х 3 случайных целых чисел в промежутке [0;10)

In [10]:
n9 = np.random.randint(0,10,(3,3))
print(n9)

[[3 7 7]
 [6 7 7]
 [5 9 2]]


Созаем единичную матрицу размером 3 х 3

In [11]:
n10 = np.eye(3)
print(n10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Изменение формы массивов

In [12]:
grid = np.arange(1,10)
print(grid)
grid = grid.reshape((3,3))
print(grid)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Слияние и разбиение массивов


In [14]:
x = np.array([1,2,3])
y = np.array([3,2,1])
print(np.concatenate([x,y]))

[1 2 3 3 2 1]


In [19]:
x = np.array([1,2,3])
y = np.array([[9,8,7], [6,5,4]])
print(np.vstack([x,y]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]


In [20]:
x = np.array([[99],[99]])
print(np.hstack([y,x]))

[[ 9  8  7 99]
 [ 6  5  4 99]]


In [21]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x, [3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


Универсальные функции